---

- hosts: worker
  tasks:
    # - name: Install python3-pip tmux chromedriver
    #   apt:
    #     name:
    #       - python3-pip
    #       - tmux
    #       - chromium-chromedriver
    #       - libappindicator1
    #       - fonts-liberation
    #       - libnss3

    # - name: Install pipenv
    #   pip:
    #     name: pipenv
    #     executable: pip3

    - name: Sync src files
      synchronize:
        src: "{{ src_path }}/"
        dest: "{{ worker_dest_path }}/"
        rsync_opts:
          - "--exclude-from={{ src_path }}/.gitignore"

    - name: Sync .env file
      synchronize:
        src: "{{ src_path }}/Tool/ansible/.env"
        dest: "{{ worker_dest_path }}/.env"
        delete: yes

    # - name: Pipenv install
    #   shell: |
    #     pipenv install
    #   args:
    #     chdir: "{{ worker_dest_path }}"

    - name: Run worker
      shell: |
        tmux kill-session -t worker
        sleep 1
        tmux new-session -d -s worker
        tmux send-keys 'htop' 'C-m'
        tmux split-window
        tmux send-keys 'pipenv run celery -A tasks worker -c 5 -l info' 'C-m'
        tmux select-layout even-horizontal
      args:
        chdir: "{{ worker_dest_path }}"