---

- hosts: worker
  tasks:
    - name: Install ffmpeg python3-pip
      apt:
        name:
          - ffmpeg
          - python3-pip
          - nfs-common

    - name: Install pipenv
      pip:
        name: pipenv
        executable: pip3

    - name: Sync src files
      synchronize:
        src: "{{ src_path }}/"
        dest: "{{ worker_dest_path }}/"
        rsync_opts:
          - "--exclude-from={{ src_path }}/.gitignore"

    - name: Sync .env file
      synchronize:
        src: "{{ src_path }}/Tool/ansible/.env"
        dest: "{{ worker_dest_path }}/.env"
        delete: yes

    - name: Pipenv install
      shell: |
        pipenv install
      args:
        chdir: "{{ worker_dest_path }}"

    - name: Mount CCNSAnime NFS
      ansible.posix.mount:
        src: "{{ anime_storage_ip }}:{{ anime_storage_path }}"
        path: /mnt/CCNS-Anime
        opts: rw,sync,hard,intr
        state: mounted
        fstype: nfs

    - name: Run worker
      shell: |
        tmux kill-session -t worker
        tmux new-session -d -s worker
        tmux send-keys 'htop' 'C-m'
        tmux split-window
        tmux send-keys 'pipenv run celery -A tasks worker -c 2 -l info' 'C-m'
        tmux select-layout even-horizontal
      args:
        chdir: "{{ worker_dest_path }}"